<Label>
    markup:1
    font_name:"C:/Windows/Fonts/ITCKRIST.ttf"

TabbedPanel:
    do_default_tab:0
    background_image:"C:/Users/Mohammad Ali Bazzazi/Downloads/bg.png"
    TabbedPanelItem:
        text:'Clock'
        background_color:"#ca45ff"
        font_name:"C:/Windows/Fonts/ITCKRIST.ttf"

        BoxLayout:
            orientation:'vertical'
            Label:
                id:timer
                text:""
                font_size:25
